create table Customer (
	customerId bigint auto_increment, 
    username varchar(64) not null, 
    password varchar(128) not null, 
    customerName varchar(64) not null, 
    customerEmail varchar(64), 
    customerPhone varchar(64), 
    enabled bool, 
    billingAddressId bigint, 
    shippingAddressId bigint, 
    cartId bigint, 
    primary key (customerId), 
    foreign key (billingAddressId) references BillingAddress(billingAddressId), 
    foreign key (shippingAddressId) references ShippingAddress(shippingAddressId), 
    foreign key (cartId) references Cart(cartId));